-- require('nvim-treesitter').setup({
-- 	injection = {
-- 		enabled = true,
-- 	},
-- })
--
-- require('nvim-treesitter.configs').setup {
-- 	highlight = {
-- 		enable = true,
-- 		additional_vim_regex_highlighting = { "htmldjango", "html" },
-- 	},
-- }
